---

- hosts: all
  become: true
  pre_tasks:
   
    - name: Install updates (Oracle Linux)
      dnf:
        update_only: yes
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "OracleLinux"

    - name: Install updates (Ubuntu)
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"
  

  tasks:
    
    - name: Install apache2 & php packages (Ubuntu)
      tags: apache,php,ubuntu
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install apache2 & php packages (Oracle Linux)
      tags: apache,httpd,php,oracleLinux
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "OracleLinux"

    - name: Create webserver admin (Ubuntu)
      tags: webadmin
      user:
        name: webadmin
        shell: /bin/bash
        group: www-data
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Create webserver admin (Oracle Linux)
      tags: webadmin
      user:
        name: webadmin
        group: apache
        state: present
      when: ansible_distribution == "OracleLinux"

